export const blogPlaceholderImages = [
  'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80',
];

export const buildPlaceholderBlogPosts = () => [
  {
    id: 'placeholder-1',
    title: 'Faith and Learning',
    slug: 'faith-and-learning',
    excerpt: 'A brief introduction to why faith-based learning matters for a whole-child education.',
    content: 'Education rooted in faith helps children grow in confidence, compassion, and purpose.',
    category: 'Faith & Values',
    category_id: 'placeholder-category',
    featured_image: blogPlaceholderImages[0],
    featured_image_alt: 'Children learning together',
    status: 'published',
    is_featured: true,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'placeholder-2',
    title: 'Early Literacy Begins at Home and School',
    slug: 'early-literacy-begins-at-home-and-school',
    excerpt: 'Strong reading foundations create the confidence children need to thrive academically.',
    content: 'Reading every day builds imagination, vocabulary, and curiosity from the earliest years.',
    category: 'Academic Life',
    category_id: 'placeholder-category',
    featured_image: blogPlaceholderImages[1],
    featured_image_alt: 'Students reading together',
    status: 'published',
    is_featured: false,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'placeholder-3',
    title: 'Sports Day Energy and Teamwork',
    slug: 'sports-day-energy-and-teamwork',
    excerpt: 'Active play inspires confidence and helps children learn cooperation and resilience.',
    content: 'Sports build fitness, social skills, and emotional confidence in a joyful way.',
    category: 'Sports & Wellbeing',
    category_id: 'placeholder-category',
    featured_image: blogPlaceholderImages[2],
    featured_image_alt: 'Students playing sports',
    status: 'published',
    is_featured: false,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'placeholder-4',
    title: 'Creative Music Lessons for Young Minds',
    slug: 'creative-music-lessons-for-young-minds',
    excerpt: 'Music training strengthens memory, expression, and creativity in a fun and supportive setting.',
    content: 'Children who learn music often show stronger focus, imagination, and emotional understanding.',
    category: 'Arts & Creativity',
    category_id: 'placeholder-category',
    featured_image: blogPlaceholderImages[3],
    featured_image_alt: 'Children in a music lesson',
    status: 'published',
    is_featured: false,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'placeholder-5',
    title: 'Building Strong School Partnerships',
    slug: 'building-strong-school-partnerships',
    excerpt: 'When schools and families work together, children benefit from consistency, trust, and encouragement.',
    content: 'Partnerships between home and school create a stronger foundation for every child’s growth.',
    category: 'Community',
    category_id: 'placeholder-category',
    featured_image: blogPlaceholderImages[4],
    featured_image_alt: 'Parents and teachers working together',
    status: 'published',
    is_featured: false,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
];
